### ISSUE TITLE
Reaching out to vendors for easier access to data

### ISSUE THREAD

**Issue by cdtyyz** [IMLS/public-libraries-survey#10]
This is primarily a rallying cry, for a change in tactics so that libraries will have easier time asking for, and getting access to, data in support of some existing and proposed new measures -- for data that resides in a vendor system.  

For circulation, holdings and borrower details, that data typically resides in the library's ILS system, and if the library is lucky enough to have a combination of an appropriately designed ILS system with flexible custom reporting options, and the knowledge and skills to generate the required reports, and/or the money required to pay someone to do it on their behalf, then getting reliable and consistent new data should not be a big issue.  Sometimes, an ILS system might even have an existing standard report output, that includes the needed data ... and so sometimes all it takes is a savvy ILS user and/or a quick phone call to their vendor rep, to find out how/where. But in all instances, this process is driven by each individual library, making the effort on their own.

For the traditional PLS measures (that have been with us for a long while), like registered users, physical volumes, circulation of print material, ... by now, every library has likely figured out how to easily extract this data from their ILS.

But what happens when a new measure is proposed?

As we've seen with other new measures, that are more recent to the PLS, the response rates can be pretty low. (e.g., circulation of electronic materials, retrievals of electronic information) despite the typical lead-up time before they are added to the survey.

It is quite possible, that some PL's are not yet providing access to electronic materials/information, but suspect that there are also many struggling to figure out how to get this data out of their vendor systems.

Given that typically, there is a very finite number of vendors -- especially those covering over 90% of the market -- it seems logical to think about centralizing the "ask" for access to such data, rather than expecting each individual library to eventually, hopefully in a consistent way, "figure it out".

In addition to the existing PLS measure for "Number of Registered Users"  
 ... we also suggest measures such as: 

Number of Active borrowers (Registered Users who borrowed during the reporting year) 
Active borrowers of e-resources (Distinct number that borrowed e-resources)
Active borrowers that only used e-resources  (Distinct number that only borrowed e-resources)

This would enable generation of a number of useful and comparable key ratios, including: 
Percentage Active Cardholders (Active/Registered)
Percentage Active Cardholders that use e-resources (Active/e-resources)
Percentage Registered Borrowers that use e-resources (Registered/e-resources) 
Percentage Active Cardholders that only use e-resources  (Active/e-resources only) 
Percentage Registered Borrowers that only use e-resources (Registered/e-resources only)  
Percentage Active Cardholders that never use e-resources  (100 - %e-resources)
etc.

These measures, especially over time, and when comparing against peers, could be very instructive in terms of what is really happening as collections typically are, after staffing costs, the most significant investment that libraries make.

Not sure if anyone else has seen the measures that PLVN (Australia) tracks ... but they include turnover rates for e-titles and book volumes.  Seems like a good idea, except they likely should be tracking/comparing vs book title turnover and not book volumes, since typically there is no corollary to e-resource "volumes" ... there is only distinct titles.  In that case, it might be useful to also ask the ILS vendors if they also can provide a list of distinct "titles" ... and not just print volumes, that is now being captured.

We also just completed the capture of some new circulation measures in the PLA PLDS survey, for 
 Average days of circulation 
and 
Days of initial circulation 

The results are quite interesting and informative, but many libraries had some difficulty reporting such data.

So this suggestion is about assembling a list of new (maybe existing to some ILS vendors) measures, that can then be requested of all the ILS vendors, where the ask is that they include these data, and/or instructions on how to get such data.  And if this request comes from IMLS and or with others jointly, then I suspect there would be a greater chance of some positive movement and more likelihood of better, more consistent data sooner.

Carl Thompson, Counting Opinions (SQUIRE) Ltd

**Comment by mgolrick** [comment]
I am going to repeat what I said on the other proposal:

"One thing I keep in mind is something that the person who hired me said - and she was my predecessor - the data elements need to be simple enough to be counted by even the smallest libraries. Some of our libraries have directors without the MLS. If we want complete, meaningful data, it needs to be able to be reported by the smallest of the units."

Let me also note that according to Marshall Breeding's annual automation survey ([https://americanlibrariesmagazine.org/2017/05/01/library-systems-report-2017/](url)) there are about 25 vendors out there … plus the open source vendors. He identifies seven (7) as public library providers, but I know that there are several systems listed under K-12 in his scheme which are used by public libraries in my state. That 25 does NOT include any open source systems. 

While this is a worthy idea to think about, and if the PLDS were to want to pursue it, I would be interested in *their* response rate, I think it is very much beyond the scope of what I can expect most of the libraries in my state to be able to answer.

On the other hand, I already collect the standard loan period for materials, and could answer that question.

I would finally add, that for me, this is a lower priority than getting the database vendors to give libraries (including mine) useful, consistent, and comparable data.

**Comment by jrnelson1201** [comment]
The proposal sounds like a good one for the next phase of Measures that Matter to take on.

**Comment by csvh** [comment]
I agree with Michael about the smallest library. 

Don't feel like opening a new issue but this somewhat applies about database use. Our statewide databases went to geolocation so no remote password, no ip address, now we have no idea where the "retrieval" is from for the statewide databases. This information is non-existent on the local pl level.

**Comment by cdtyyz** [comment]
State Wide Databases ... hmm ... maybe should be reported on the States vs
PLS survey? Then individual PL’s wouldn’t  need to do anything.

And for these State-wide Databases do you “authorize” access based on
geolocation but not log the geolocation details when recording accesses?
If that data is logged then feasible to allocate based on geolocation of
nearest PL outlet ... if such attribution is needed.

**Comment by cdtyyz** [comment]
One of the reasons to reach out to vendors (whether that is 25, 50 or even 100 of them) is that it is primarily a one-time activity to a finite easily countable number of them, and even if they all were not on-board or capable of handling everything requested, I suspect that the 80-20 rule would apply, whereby 80% of the install base of libraries would be covered with 80% of data requests becoming automated, if the top 20% of the vendors (by install base) participate.  And I suspect participation by vendors could be much higher than that.  Contrast contacting that number of vendors once ... vs contacting 1000's of small libraries each year to provide such data, and it seems reasonable to assume that a centralized ask of vendors could save effort for 1000's of small libraries each year.  And Michael, yes, no doubt even small libraries have reliably and consistently been providing circulation statistics each year, but that says nothing about how reliable or consistent those results are compared to others. The idea of reaching out to vendors, therefore, is 3-fold.  1) Reduce the burden of reporting such data by all libraries ... especially those without the staff/know how to collect such data on their own; 2) Increase the reliability and consistency of the reported data; 3) Ensure that vendors become part of the solution moving forward, and not part of the problem.  Notice that I did not recommend such an approach for the router vendors for capture of wireless sessions. That is a totally different marketplace where there are significantly more challenges with such an approach.  First and foremost, router vendors are not specific to the library marketplace and therefore it is questionable as to how much an "ask" from the library profession will influence such vendors, especially for the existing install base of equipment. Secondly, without a "Marshall Breeding" style reference, it is difficult even knowing which wireless vendors to contact. And finally, routers have been in use in libraries for about half as long as ILS systems and I am guessing that the central functions of the ILS systems are better understood (collectively if not individually) by the profession than routers. To most, a wireless router is just a "black box" with no user interface at all with access restricted to only the most technical of IT types.  It is not that such an approach should not be considered with wireless vendors, I am merely suggesting that such an approach with ILS vendors is likely to be far more satisfying.  And again, there is no suggestion here that small libraries need to do anything, other than follow the instructions provided by the vendors, which ideally is nothing more sophisticated than "login and choose "X" from the menu to run the report for your FY summary results"
