### ISSUE TITLE
A Count of Library Cards Issued to Juveniles

### ISSUE THREAD

**Issue by bobwetherall** [IMLS/public-libraries-survey#11]
The PLS has long counted the total number of registered users of each public library.  This new data element would count the number of juvenile cards issued by the library.  Even though many parents use adult cards to check out juvenile materials for their children, in Delaware we feel it is very important to get library cards into the hands of kids.  To this end, Delaware has developed two new statewide cards:  a My First Card for children birth through age 5, and a Kids Card for children 6-12.  To entice parents to request these cards for their children, fines are waived for juvenile materials checked out.

There is a significant movement to attract more juvenile borrowers on a nationwide basis.  We want to link reading achievement and reading scores in the schools to use of libraries.  By counting juvenile registrations we can begin to get a handle on this issue.  Data for this element would be readily available to public libraries.  

I have attached a spreadsheet showing national rankings for children's services.
[National Juvenile stats (2).xlsx](https://github.com/IMLS/public-libraries-survey/files/2319442/National.Juvenile.stats.2.xlsx)

**Comment by juantlee** [comment]
- QUESTION FOR CLARIFICATION: Would this be the count of how many cards were issued to children during the past year? Or is it the total number of registered users who are children?

- Either way, in Utah, coming up with a number of cards held by children will be difficult as some of our "less sophisticated" libraries may not enter a birth date on the patron record or the card may be a "family" card. BTW, if the reporting library has family cards, my advise is to give me the number of records and NOT to try to estimate the number of individual per family.

**Comment by bobwetherall** [comment]
Juan,


Either, or both would be fairly easy to obtain from libraries' automation systems.  I was thinking of total cards held by juvenile borrowers.  You do bring up valid points, and it could be a challenge getting an accurate number.  For example, when we look at the number of cards with a juvenile profile we get a different number than if we look at ages.  Obviously, many patrons don't change their cards over to adult cards when they reach 18.  But I think we have to start to get a handle on this.  Here in Delaware we are trying to get parents to get cards for their children so they can take responsibility for their reading.


?

________________________________
