### ISSUE TITLE
Expedite the release of PLS Data

### ISSUE THREAD

**Issue by eplagman** [IMLS/public-libraries-survey#14]
Name: Emily Plagman

State: Public Library Association

Title of the proposed data element: Release unimputed data of PLS data sooner

Rationale for addition: We have heard from our members that they would like/need PLS data much sooner for their annual budgeting and planning cycles. I understand this has been discussed in past forums but I'd like to keep the conversation going in hopes of it happening sooner rather than later.

Any states that are already collecting this information: n/a

**Comment by ThomasIvie** [comment]
The IMLS has done a good job of decreasing the amount of time that it takes to get the PLS data out to the public. Currently, data through 2017 is available. We've just finished the 2018 reporting cycle, so I would say that is extremely good. Compare that with most federal agencies that are 2-3 years out on releasing data.
