### ISSUE TITLE
Proposed Change (652 - Wireless Sessions)

### ISSUE THREAD

**Issue by johnkerber** [IMLS/public-libraries-survey#15]
**Current Definition:** Report the number of wireless sessions provided by the library wireless service annually.

**Proposed Addition to Current Definition:** A session is counted each time a “patron” device connects to the wireless network. When a “patron” MAC address is identified on the network the session begins and after the network stops detecting it for a period an hour, it is closed. Should the device reconnect afterwards during the same day a new session should begin following the same logic. Should the device stay on the network overnight, at midnight the previous session will close and a new session will begin. Sessions should only be counted for patron devices and should not include library devices such as routers, access points, printers, and public access computers.

**Rationale for Change:** The purpose of refining the definition of the requirement is to standardize the data being collected. There are numerous ways this element can be counted in the absence of guidelines around the requirement. The removal of library equipment allows the isolation of patron devices. This will allow the directors the ability to better see how patron’s are utilizing their locations. Texas has already required the exclusion of library equipment.

**Comment by mgolrick** [comment]
There is still significant difficulty in collecting data under the current definition, even in states which have been collecting it for a number of years. This level of specificity is too detailed for most libraries, and I have a concern that libraries will simply stop collecting any data if we ask at this level.

Is it desirable? Yes. Is it best practice? Likely. Is it able to be done? No.

I could support adding the last sentence as a clarification to the current definition, however.

**Comment by timrohe** [comment]
I agree with the majority of Michael's response.  The only thing with which I disagree is adding the removal of library equipment to the definition.  I understand the thinking behind it but, for my libraries, I fear any additional collection burden would make the response rate drop precipitously.  I already get complaints that this data is a pain to collect; if I add even the slightest layer of difficulty on top of it, I feel like most of my libraries would simply select 'Unavailable.'

**Comment by johnkerber** [comment]
Thank you for providing us with this thoughtful feedback on the proposal.  It is great to hear that the proposed changes are desirable, and that they likely describe a best practice, but we also understand how these changes may seem daunting when there are libraries who may already be struggling to provide data under the current definition.  However, the emerging technology of WiFi Analytics contains a variety of user-friendly, cost-effective solutions to obtain the information described in the proposal as well as the information currently requested by the IMLS in the Annual Survey.  

As you may already know, we are a provider of WiFi Analytics that has made custom-tailored modifications to better serve public libraries, such as protecting the anonymity of patrons while still collecting accurate data. If you have any questions regarding WiFi Analytics, we would like to offer ourselves as an information resource to you and the members of the Library Statistics Working Group.  Alternately, we would also recommend contacting the state libraries of South Dakota, Ohio, and Virginia regarding their experiences with how libraries across their states have employed WiFi Analytics to gather this information.

**Comment by Chilcoat** [comment]
I agree with both Michael and Tim in avoiding anything to further complicate the collection of this statistic for our smaller libraries--which is most of our libraries in a rural state like Arkansas.  Additionally, they will not have additional funds to spend on software to collect this data.  I am figuratively dying to know how much use our libraries' Wi-Fi is getting, but I think we're not there yet.
