### ISSUE TITLE
Proposed Addition: New Data Element, Wireless Session Time

### ISSUE THREAD

**Issue by johnkerber** [IMLS/public-libraries-survey#16]
**New Definition:** Report the total wireless session time and average wireless session time provided by the library wireless service annually.

Total wireless session time can be recorded by totaling all wireless session times for a year. Average wireless session time can be derived by dividing the total wireless session time by the total wireless session counts (data element 652).

**Rationale for Addition:** To accurately compare how public wireless services are utilized by patrons across locations, knowing both the wireless counts and wireless time give a more accurate representation.

**Comment by mgolrick** [comment]
Not possible.
There are already issues with collecting this data, even in states which have been collecting it for many years.
While it may be valuable information, and desirable to have this, it is not possible to do so for most public libraries in the country.

**Comment by timrohe** [comment]
Again, I agree with Michael.

**Comment by johnkerber** [comment]
Thank you for the feedback on this new data element.  Please see my comment on the proposed change to data element 652.
