### ISSUE TITLE
Proposed Definition Clarification: 502 Reference Transactions

### ISSUE THREAD

**Issue by lfrehill** [IMLS/public-libraries-survey#18]
**Name**: Lisa M. Frehill

**State**: IMLS

**Title**: Change Data Element Definition (and related instructions)

**Data Element**: 502 - Reference Transactions

**Overview**: The proposed change revises the main part of the definition to be the same as RUSA's definition. Various additional instructions about what to include (or note include) are retained as "notes", which would be numbered. Finally, instructions related to using an estimate rather than an actual count (i.e., extrapolating from some number of weeks to the full year) would be delimited from the rest of the definition and clearly marked as such. The attached file shows the original and proposed data element documentation with comments about each of the segments.

**Rationale**: IMLS data element review research indicated that the lengthy definition was confusing for those who enter data. Proposed instrumentation seeks to separate the actual definition from notes and other information related to how individuals can report on reference transactions. 
[RefTrans_Github.docx](https://github.com/IMLS/public-libraries-survey/files/3553299/RefTrans_Github.docx)

**Comment by kjcmetzger** [comment]
I have two questions.
1) Could someone clarify what "computer-assisted instruction" is?
2) In RI, we have explicitly told libraries **not** to include one-on-one technology assistance in Reference Transactions. However, reading the current text again, 

> "unscheduled individual instruction and assistance in using information sources (including websites and computer-assisted instruction)" 

does lend itself to the interpretation that one-on-one technology instruction is included. If we are revising this definition, perhaps we could also put language in the definition that states one-on-one technology assistance is **not** a reference transaction.

**Comment by mgolrick** [comment]
The current definition is meant to *include* when a reference librarian works with someone on an unscheduled basis to figure out an office productivity program, or to help someone find the link to apply for jobs on the McDonalds web site. (I do this daily!) What is and was meant to be excluded was teaching a class on buying/selling on eBay, or a one hour presentation on Fake News. One-on-one technology assistance is a critical part of reference today (in my view), and the intent always has been to count it.
