### ISSUE TITLE
Addition - 502a - Reference Transactions Reporting Method

### ISSUE THREAD

**Issue by lfrehill** [IMLS/public-libraries-survey#19]
**Name**: Lisa M. Frehill

**State**: IMLS

**Title**: New element associated with reference transactions data (element 502)

**Proposal**: Data element 502 provides instructions for data enterers: " If an annual count of reference transactions is unavailable, count reference transactions during a typical week or weeks, and multiply the count to represent an annual estimate." The proposed revised definition labels this instruction as: "Annual Count Versus Annual Estimate". A question would be asked with two fixed choices:

Regarding the number of reference transactions you entered, is this an:
  _ annual count
  _ annual estimate based on a typical week or weeks. 

**Rationale**: The new element provides a mechanism to allow data users to make more precise comparisons (e.g., analyzing only those that included an annual count separately from those that are estimates based on typical week methods). It would not impact current reporting but would offer additional analytical flexibility. 

States that do something like this already:
Idaho, North Carolina, and Wisconsin (see attached)
[PLS State Methods Examples.docx](https://github.com/IMLS/public-libraries-survey/files/3556950/PLS.State.Methods.Examples.docx)

**Comment by dennisonmich** [comment]
Will you also propose this for 501 Library Visits (VISITS) or 651 Number of Uses (Sessions) of Public Internet Computers per Year (PITUSR) which also allow for a "typical week" or, in the case of PITUSR, "other reliable estimate"? I agree that adding this will be useful, and the fix should be universal to elements where estimates are allowable and not just for 502 Reference Transactions (REFERENC).

**Comment by lfrehill** [comment]
I added a similar item for the 501 but for 651, the wording on the definition is a little less specific than that on 501 and 502. The proposed method items mirror the wording used within 501 and 502 ... but that's less clear for 651.

lisa

________________________________

**Comment by yanademireva** [comment]
Same comment as on 652 - I just want to better understand exactly how this knowledge help things like decision-making at the system level, at our level, etc. I can see the potential for its usefulness, but want a better picture.

Yana

Yana Demireva
Research & Evaluation Coordinator
Maryland State Library

**Comment by Chilcoat** [comment]
We in Arkansas already ask for this distinction, so it wouldn't be a change for our libraries.  We also already make the distinction for VISITS and PITUSR.
