### ISSUE TITLE
Deletion - 500 Public Service Hours Per Year (HRS_OPEN)

### ISSUE THREAD

**Issue by enielsen-air** [IMLS/public-libraries-survey#21]
**Name:** Evan Nielsen
**State:** N/A (American Institutes for Research)

**Data Element:** 500, Public Service Hours Per Year (HRS_OPEN)
**Current Definition:** "This is the sum of annual public service hours for outlets."

**Rationale for Deletion:**
To be clear, I am only proposing that HRS_OPEN be removed from the data collection, not from the data files. The outlet data element HOURS would be retained and used to populate HRS_OPEN. In FY 2017, edit checks for consistency between HRS_OPEN (500) and HOURS (713) occurred more than 1,500 times. If HRS_OPEN should simply be the sum of HOURS values for the outlets in that AE, then the value for HRS_OPEN should be a calculated field, instead of reported. This would eliminate the burden of resolving these inconsistencies.

**Comment by yanademireva** [comment]
I agree that a calculated field would eliminate inconsistencies, and streamline the process for libraries. 

-Yana

Yana Demireva
Research & Evaluation Coordinator
Maryland State Library
