### ISSUE TITLE
Formal Vote

### ISSUE THREAD

**Issue by ThomasIvie** [IMLS/public-libraries-survey#23]
**Name:** Thomas Ivie
**State:** Wyoming

**Proposal:** A formal vote (binding or otherwise) of the State/Territorial Data Coordinators that only SDC;s may submit proposals to add/delete PLS data elements, or changes thereto, and the result of said vote will be expedited to COSLA for discussion or vote as they prepare for their November, 2019 meeting. 

**Rationale:** In order to avoid conflict of interest and because IMLS, vendors, and other interested parties are not the ones voting to send proposals on to COSLA.

**Comment by lfrehill** [comment]
**Name**: Lisa Frehill
**State**: IMLS

This is the first year that I submitted some proposals related to data elements. I also noted that Evan Nielsen from AIR also submitted one. It seems like a useful forum within which to get some discussion about potential items that are based on the research that IMLS has done over the past three years (the data element review), some of which was performed by AIR. In other words, I understand the concerns about the posting by other vendors, but in our case (IMLS and AIR), our suggestions are not about expanding a market, but derived from research about the PLS to increase utility and reduce burden of the PLS. 

I am finding the comments very helpful from a methodological standpoint.

**Comment by ThomasIvie** [comment]
Hi Lisa!
I don't disagree with you. However, there is a distinct difference between discussion and proposals. Please correct me if I'm wrong (and I could very well be), but I thought this site was set up for proposals to be voted on. In addition, there is a distinct difference between those who attend the annual meeting and those who do not and are not invited. This isn't a platform for any vendor with an agenda to increase sales to make proposals to facilitate that goal. Maybe we need a more discreet venue.

**Comment by mgolrick** [comment]
I think that a broadening of those able to submit changes to include the Chiefs, IMLS staff, and IMLS contractors would make it much more amenable. I could support broadening that far. (Only SDCs may be too narrow a pool - as much as I love my fellow SDCs!)
