### ISSUE TITLE
Revision to Website Visits (653, WEBVISIT)

### ISSUE THREAD

**Issue by timrohe** [IMLS/public-libraries-survey#24]
Current Definition:

653 Website Visits (WEBVISIT)

Visits represent the annual number of sessions initiated by all users from inside or outside the library to the library website. The library website consists of all webpages under the library’s domain. A website “visit” or “session” occurs when a user connects to the library's website for any length of time or purpose, regardless of the number of pages or elements viewed. Usage of library social media accounts (e.g., Facebook, Twitter, etc.) should not be reported here. Libraries unable to collect a count of their website visits should report “-1” (missing). Libraries without websites should report “-3” (not applicable). (Missing values will be imputed in the final dataset, whereas values of not applicable will not be imputed.)

Revised Definition:

653 Homepage Visits (WEBVISIT)

Visits represent the annual number of visits initiated by all users from inside or outside the library to the homepage of the library’s website. A website “visit” occurs when a user connects to the library's homepage for any length of time or purpose. The homepage is the initial or main page of the library’s website.  The library’s homepage may be a top-level domain of the library’s unique website, or a second-level page on the website of another administrative agency, such as a municipality or school. The homepage provides information about the library and/or facilitates navigation to other pages of interest, such as the library’s online catalog. Usage of library social media accounts (e.g., Facebook, Twitter, etc.) should not be reported here. Libraries unable to collect a count of their website visits should report “-1” (missing). Libraries without websites should report “-3” (not applicable). (Missing values will be imputed in the final dataset, whereas values of not applicable will not be imputed.)

Justification:
•	The majority of SDCs expressed concern that they did not trust the data being reported by libraries in their state/territory.
•	The most frequently cited concern was that, when libraries do report data, the number given was overly inflated.  This is largely due to confusion surrounding the definition.
•	The confusion largely stems from libraries being unclear on the definition of a “domain” and how to group hits into a “session.”
•	Anecdotally, libraries whose webpages are part of another entity’s website (municipality/school/etc.) are reporting inconsistencies.  The erroneous  values reported include:
     -  Hits to the library’s homepage, with the library citing an inability to individually track hits to all of their disparate webpages and group them into a “session.”
     - The summation of individual hits to all of the library’s webpages, citing an inability to group them into the required “sessions.”  This results in an overly inflated number.
     - ‘Unavailable.’
•	With the majority of the data being unreliable or unavailable, the definition should be modified to make it:
     - More clear
     - Easier to collect and, therefore
     - Easier to report
•	Decreasing the collection burden would increase reporting of the data from libraries that had formerly selected ‘Unavailable.’
•	The increased consistency of only reporting visits to a library’s homepage makes the data more comparable across libraries.

The benefits of decreasing the collection burden, increased reporting, increased accuracy of the reported data, and greater comparability across libraries outweighs the loss of click-throughs on subpages that had previously been included in the definition for “sessions.”

**Comment by Chilcoat** [comment]
I'm wondering about the exclusive use of the homepage for counting visits/sessions.  If a person has a shortcut or different path to the elements of the website, without starting out at the homepage, would that still be counted?  I feel that the terminology included in the original definition of "regardless of the the number of pages or elements viewed" gets us closer to what we're actually trying to measure than limiting counts to visits that hit the homepage.

**Comment by timrohe** [comment]
No, it would only count hits the homepage, not "sessions" to all pages under the libraries “domain.”  I agree that, in theory, the idea of counting “sessions” that access “the library's website for any length of time or purpose, regardless of the number of pages or elements viewed” sounds better in theory.  However, in practice, many of my libraries found it to be unworkable for all of the reasons listed above and I do not trust the numbers being given at all.

To be quite candid, both Patrick and I were in favor of deleting this data element, and I'm still not opposed to that.  I just felt it unlikely, since it was very recently added and now Library Journal is going to add it as one of their metrics to consider libraries for a star rating.  Therefore, I scaled it down to something that I feel is easier to track and more comparable across libraries: hits to the homepage.  Most libraries can point to their homepage, whether they host/administer it themselves or that's done for them by someone else, like a municipality, and would be able to get the hits to at least that page.  Even hits to the homepage is still a garbage number, in my opinion, though, since most libraries have their public computers set to load on the library's homepage, but whatever.
