### ISSUE TITLE
Revision - 652 Wireless Sessions (WIFISESS)

### ISSUE THREAD

**Issue by enielsen-air** [IMLS/public-libraries-survey#25]
**Submitter:** Evan Nielsen, AIR

**Data Element:**
652 Wireless Sessions (WIFISESS)

**Current Definition:**
Report the number of wireless sessions provided by the library wireless service annually.

**Revised Definition:**
Report the number of wireless sessions provided by the library wireless service annually. Count one session for each time a device connects to the library's wireless network, regardless of the duration of connection. If possible, only count sessions for patron devices and exclude library devices such as routers, access points, printers, and public access computers; otherwise, if patron devices cannot be isolated, report sessions for all devices. 
NOTE: If an annual count of wireless sessions is unavailable, count wireless sessions during a typical week or weeks, and multiply the count to represent an annual estimate. A “typical week” is a time that is neither unusually busy nor unusually slow. Avoid holiday times, vacation periods for key staff, or days when unusual events are taking place in the community or in the library. Choose a week in which the library is open its regular hours.

**Rationale:**
As discussed during the December 2019 SDC and LSWG meetings, we can only ask whether WIFISESS is an annual count or estimate if the definition explicitly allows for reporting an estimate. Thus, this added note was based on the language in Reference Transactions.
Also, the definition could benefit from being more parallel to 651 Uses of Public Internet Computers (PITUSR), so added instructions about what to count as a wireless session.

**States already collecting:**
Arkansas, New Mexico, and Wisconsin

**Comment by ghost** [comment]
How does a library estimate wireless use? Do they count every time they see a cell phone enter the building? What about external or after hours connections? We would definitely need a stronger definition if we allowed for estimates for this data element.

**Comment by enielsen-air** [comment]
Excellent point, @sdermont . To be clear, I only proposed this change because it was discussed at the SDC/LSWG meetings last December that changing this data element would be necessary in order to ask whether libraries are reporting actual or estimated counts.  If we assume that a value for WIFISESS is an estimate if it ends in at least two zeros, then there were at least 580 libraries reporting estimates for FY 2018 (or 8.75% of libraries that reported a value greater than 0), even though the definition doesn't currently allow for it.  There were 8 states in which 15% to 25% of AEs (that reported a value greater than 0) reported a value for WIFISESS ending in at least two zeros.

**Comment by vdgreenwood** [comment]
@sdermont, Some libraries can only get the data from the server for a specified amount of time, based on their relationship with the service provider.  These are primarily our larger libraries, and they report an annualized estimate.

I have tried to strongly dissuade librarians from counting the number of devices coming in the door, and emphasized that this amount is best obtained using router software, and/or consulting with their IT staff.  

Valicia Greenwood
Library Data Coordinator
Texas State Library and Archives Commission

**Comment by ghost** [comment]
Hi Valicia,

That actually makes more sense to me. I wouldn't have a problem with an
estimate based on router data. But I would still discourage libraries from
making an estimate based on counting devices.

Scott

*Scott Dermont* Library Consultant
*State Library of Iowa* | Des Moines Office
515.281.7573 | scott.dermont@iowa.gov <First.Last@iowa.gov>
1112 E. Grand Avenue | Des Moines, IA 50319
www.StateLibraryofIowa.org <http://www.statelibraryofiowa.org/>
