### ISSUE TITLE
Can STATSTRU, STATNAME, and STATADDR be combined?

### ISSUE THREAD

**Issue by mgolrick** [IMLS/public-libraries-survey#29]
When there are status changes (rare), name changes (not so often), and street address changes/corrections (fairly frequent), I have to go to the book and look through the multiple choices.

It occurred to me this year that the codes are unique to each grouping, that is, other than the "00 - no change from prior year" code, all of the others are unique. For example "07" is used only to indicate that the AE or outlet has changed its physical location, and "15" shows a minor address change. Neither code is used for a STATSTRU or a STATNAME code. Likewise their codes are unique. It would make the change process (and instructions) much simpler. (Says he who just wrangled and wrestled his data into data submission.)

**Comment by enielsen-air** [comment]
Michael, I have also noticed that the codeframes do not overlap for the three variables.  However, I think the reason they are separate fields is that it is possible for a library to have more than one status change per cycle (e.g., Structure and Address).  If these fields were combined, either we would only be able to track one of those status changes or we would have add values to account for every combination of the three status changes.  I don't think either of those options is preferable to the status quo.

**Comment by rossfuqua** [comment]
I completely agree with Evan. We have too many status changes (of various flavors) in Oregon to have these fields dependent upon one another.
