### ISSUE TITLE
Revision - 650 Number of Internet Computers Used by General Public (GPTERMS)

### ISSUE THREAD

**Issue by timrohe** [IMLS/public-libraries-survey#30]
Current Definition:

Report the number of the library’s Internet computers [personal computers (PCs) and laptops], whether purchased, leased, or donated, used by the general public in the library.

Revised Definition:

Report the number of the library’s Internet computers [personal computers (PCs), laptops, and tablets], whether purchased, leased, or donated, used by the general public in the library. Do not include computers that connect to the Internet for a dedicated purpose (e.g, to access an OPAC or specific database, or to train the public) or purposes.

Rationale for the Change:
- The current definition is overly broad and includes any computer used by the public that is connected to the Internet for any reason, including dedicated OPAC terminals.
- The revised definition is consistent with the definition used in the SLAA survey.

**Comment by ghost** [comment]
Refine the definition to include current technology and trends. I would include tablets for in-house use in this definition. Many libraries are moving away from PC's and laptops and moving towards tablets. Only count them if they are for in-house use only.

An alternative would be to remove this data element altogether. Do we still need to know how many computers a library has? That seems like an important thing to know in 1998, but in 2020, it isn't as relevant. I think use of those devices is still useful knowledge, but number of devices is getting to be pretty irrelevant.

**Comment by timrohe** [comment]
Scott, that's a good point about tablets and I have revised the proposed definition to include them. To your other point, I don't think that now is the right time to do away with this data element.  Every article I read about services offered during the pandemic mentions public computers.  In house terminals are being cited as one of the main reasons for reopening library buildings to the public, especially for those libraries (mostly small, rural ones) that don't have laptops or tablets to circulate.  I think that, if we removed it now, libraries might feel cheated.  Also, if we're going to keep counting public computer sessions, I think it's useful to know how many computers we're talking about being used for those sessions.

**Comment by ghost** [comment]
Hi Tim,

Thank you for adding tablets to the list. It sounds like there is still
value in keeping this data element in the survey so I think it helps to
improve the definition.

Scott

*Scott Dermont* Library Consultant
*State Library of Iowa* | Des Moines Office
515.281.7573 | scott.dermont@iowa.gov <First.Last@iowa.gov>
1112 E. Grand Avenue | Des Moines, IA 50319
www.StateLibraryofIowa.org <http://www.statelibraryofiowa.org/>

**Comment by Chilcoat** [comment]
I do use this data element, mostly to run the math against the number of sessions (PITUSR) so that I can see how heavily the computers they have are being used.
