### ISSUE TITLE
Addition - 459 Other Circulating Physical Items

### ISSUE THREAD

**Issue by timrohe** [IMLS/public-libraries-survey#32]
Proposed Definition:

Other Circulating Physical Items 459

Report a single figure that includes the following: all circulating physical items other than print books (450), physical audio units (452), physical video units (454), and serials.  These are materials in a fixed, physical format available for use outside the library.  These can include a variety of items types, such as wi-fi hotspots, sewing machines, cake pans, tools, etc.
Report the number of units, including duplicates. Items packaged together as a unit (such as a set of cookie cutters) and checked out as a unit are counted as one physical unit.

Justification:

•	Many libraries offer such non-traditional physical items for “use outside the library,” but there is no data element on the PLS with which to account for them in the collection.  Therefore, without such a data element, the PLS does not accurately reflect the current state of library collections across the US.
•	Data element 553 Physical Item Circulation (PHYSCIR) accounts for, “The total annual circulation of all physical library materials of all types,” but there is no corresponding data element for total physical items in the collection.  This is in part because you cannot have such a data element without accounting for these other circulating physical items in the collection.
•	The three data elements I am proposing (Other Circulating Physical Items 459, Total Physical Items in Collection 460, Circulation of Other Physical Items 557) should be considered together, as they do not make sense to implement individually.

States already collecting:
Connecticut, Iowa, Arkansas, Ohio, Virginia, Illinois, Mississippi, Indiana

**Comment by kjcmetzger** [comment]
Rhode Island also collects this.
