### ISSUE TITLE
Addition - 557 Circulation of Other Physical Items

### ISSUE THREAD

**Issue by timrohe** [IMLS/public-libraries-survey#34]
Proposed Definition:

Circulation of Other Physical Items 557

Circulation of all physical items other than print books (450), physical audio units (452), physical video units (454), and serials, including renewals.  These are materials in a fixed, physical format available for use outside the library.  These can include a variety of items types, such as wi-fi hotspots, sewing machines, cake pans, tools, telescopes, board games, video games, etc.

Justification:

•	Many libraries offer such non-traditional physical items for “use outside the library,” but unlike other physical collections (print materials, audio-physical units, and video-physical units), there is no data element on the PLS with which to account for their individual circulation.  Therefore, without such a data element, the PLS does not accurately reflect the current state of circulation of collections across the US.
•	Data element 553 Physical Item Circulation (PHYSCIR) accounts for, “The total annual circulation of all physical library materials of all types,” including these “other” physical items. While most items included in 553 are also counted as part of separate data elements for their unique physical collections (print, audio, and video units), there is no corresponding data element to track the circulation of these other physical items in the collection.  Hence, I am proposing one that would account for these items and close that gap in the summation of 553.
•	The three data elements I am proposing (Other Circulating Physical Items 459, Total Physical Items in Collection 460, Circulation of Other Physical Items 557) should be considered together, as they do not make sense to implement individually.

States already collecting:
Connecticut, Iowa, Arkansas, Ohio, Virginia, Illinois, Mississippi, Georgia, Rhode Island

**Comment by yanademireva** [comment]
I'm pretty confident that libraries collect this information already, and it wouldn't be difficult to get them to report it under a new data element.

**Comment by vgetahun** [comment]
I hadn't realized until thinking through this proposal that Minnesota doesn't have separate data elements for physical audio or video circulation, although we do have state-level data elements under both collections and expenditures that break out amounts for print, audio, video, and any other physical items. If we add a data element to the PLS to report other physical circulation, I think we would also add state-level elements to track print and physical audio/video circulation.

**Comment by timrohe** [comment]
@vgetahun I don't either, to be honest with you.  To be fair, there's no separate element for print circulation.  I find it all a little complicated.  We track physical holdings individually by format (print, A/V, etc.; 450, 452, 454) and track physical circ. by both collection (Children's circ.; 551) and then just the catch all of general Physical Item Circulation (553), with 551 included in 553.  So, if we did have separate elements for print, audio, and video, they would likewise have to include children's materials.

I'm not necessarily opposed to breaking out circ. by format in order to correspond more directly with the holdings numbers, but that's not what I was building up to.  I was just trying to address the disparity that Physical Item Circulation (553) does explicitly include these types of other physical items, but there is no place to include them in the holdings numbers.  I can see now how that might be a little confusing and how you maybe don't strictly _**need**_ a separate circ. line for these, since we don't have it for others.
