### ISSUE TITLE
Revision - 600/603 Total Number of/Attendance at Library Programs (TOTPRO/TOTATTEN)

### ISSUE THREAD

**Issue by enielsen-air** [IMLS/public-libraries-survey#35]
**SUBMITTER:**
Evan Nielsen (AIR) on behalf of IMLS and the LSWG PLS Methods Ad Hoc Subcommittee

**EXISTING DATA ELEMENTS:** 
- 600 Total Number of Library Programs (TOTPRO)
- 603 Total Attendance at Library Programs (TOTATTEN)

**RATIONALE:**
This proposal is one of three interrelated proposals for changes and additions to the library programs data elements. The SDCs and the LSWG have indicated a need to gather additional data about library programming since it is such an expanding and changing library service. A series of data elements were developed based on a review of existing state library surveys and the IMLS State Program Report system. The potential data elements were vetted in one-hour interviews with nine respondents from public libraries of various sizes in seven different states. The interviews informed the work of an ad hoc subcommittee of LSWG members and staff from IMLS and AIR to refine the revised data element definitions proposed here. 

**PROPOSED DEFINITIONS:**
See attached file (link below) for the proposed definition revisions.
[PLS Program Items_Definition and Totals.docx](https://github.com/IMLS/public-libraries-survey/files/5165157/PLS.Program.Items_Definition.and.Totals.docx)

**Comment by timrohe** [comment]
I think that, for the most part, I can see the impetus behind these changes and think they do add some clarity.  However, I though that the general consensus from the discussions on the listserv was that prerecorded (asynchronous) videos posted on the library's website or Facebook page are not "programs."  I could be wrong, but I know that I, personally, am opposed to adding them into the definition of what qualifies as a program or program session.  

The reason being is that, with live-streamed programs, there is still the element of audience participation that I believe goes to the spirit of the definition of a program.  Counting synchronous viewers is also akin to counting the audience at a live program.  With prerecorded programs, there is no audience, hence no possibility of audience participation and counting asynchronous views over the course of the fiscal year is fundamentally different than even synchronous views, with no relation at all to attendance at a live program.  You're counting two different but similar enough varietals of apples and oranges.

If we want to count prerecorded content with their subsequent asynchronous views, I think they should be a separate entities and not counted as "programs."  I was planning on adding prerecorded videos and views as a local question this year, but mainly for the same reason I have a local question for passive programs, to keep people from counting them in the official program numbers that get passed on to IMLS.

**Comment by yanademireva** [comment]
The clarification of the definitions is definitely helpful, especially around sponsorship and what constitutes an offsite program.

**Comment by mihalc** [comment]
I appreciate the clarification in definitions, but do have reservations about the addition of recorded programming to total program counts. I think once have to explain not to count passive or self-directed activities **except** pre-recorded programs we are acknowledging that there is a problem here. If we were to create a passive programming category that counted pre-recorded programs, I think that would be acceptable, but this is, in my eyes, a passive program which has never been included in programming counts. I will also say that this will remove any comparability between program and attendance numbers before and after the implementation of this change.
