### ISSUE TITLE
Training Example: Proposed Addition to Data Elements--Ice Cream Consumption

### ISSUE THREAD

**Issue by MarisaPelczar** [IMLS/public-libraries-survey#4]
**Name:** Marisa Pelczar

**State:** IMLS

**Title of the proposed data element:** Ice cream consumption

**Definition:** This is the total number of ice cream cones eaten during the summer. 

**Rationale for addition:** It is important to measure ice cream consumption year to year to ensure we are eating enough ice cream. 

**Any states that are already collecting this information:** State1, State 2, State3

**Comment by MarisaPelczar** [comment]
I think we should measure ice cream sandwiches instead of ice cream cones.

**Comment by mgolrick** [comment]
I like the idea of tracking consumption, I only eat ice cream sandwiches in the winter, so I think cones is the correct unit of measurement.

**Comment by bsweezy** [comment]
We could consider using the standard managed by the International Dairy Foods Association--they seem to focus on "gallons of ice cream" in order to capture a wide variety of products.

http://www.idfa.org/news-views/media-kits/ice-cream/ice-cream-sales-trends

**Comment by jrnelson1201** [comment]
I'm a little concerned we're focused on tracking just numbers, not impact. Is there a way around that? :-)

**Comment by JenClifton** [comment]
I think we need to define "ice cream" - does it need to contain cream? Or should we count non-dairy frozen desserts or sorbets as well?

**Comment by juantlee** [comment]
I believe JenClifton makes a good point. I am sure [Arizona ](https://www.azlibrary.gov/libdev/programs-services-and-tools/arizona-public-library-statistics)has a different definition of ice cream than [Alaska](http://library.alaska.gov/dev/plstats/plstats.html).

**Comment by MeganSchulz** [comment]
In order to count "ice cream cone" consumption, do we count only IF the cone was also eaten or can we count if just the ice cream itself on top of the cone was eaten?
