### ISSUE TITLE
Deletion: 455 Video – downloadable units (VIDEO_DL)

### ISSUE THREAD

**Issue by KathleenSullivan** [IMLS/public-libraries-survey#40]
**Your names**: Kathleen Sullivan (WA), on behalf of the SDC Electronic Materials FAQ Working Group (Yana Demireva (MD), Chris Guerra (AZ), Joseph Hamlin (MI), Kelly Metzger (RI), Kathleen Sullivan (WA))

**Number and title of the data element proposed for deletion**: 455 Video – downloadable units (VIDEO_DL)

**Current definition:** These are downloadable electronic files on which moving pictures are recorded, with or without sound. Electronic playback reproduces pictures, with or without sound, using a television receiver, computer monitor or video-enabled mobile device. Video – Downloadable Units may be loaned to users on portable devices or by transmitting the contents to the user’s personal computer for a limited time. Include Video – Downloadable Units held locally and remote Video – Downloadable Units for which permanent or temporary access rights have been acquired.

Report the number of units. Report only items that have been purchased, leased or licensed by the library, a consortium, the state library, a donor or other person or entity. Included items must only be accessible with a valid library card or at a physical library location; inclusion in the catalog is not required. Do not include items freely available without monetary exchange. Do not include items that are permanently retained by the patron; count only items that have a set circulation period where it is available for their use. Count electronic materials at the administrative entity level; do not duplicate numbers at each branch.

NOTE: For purposes of this survey, units are defined as “units of acquisition or purchase.” The “unit” is determined by considering whether the item is restricted to a finite number of simultaneous users or an unlimited number of simultaneous users.

Finite simultaneous use: units of acquisition or purchase is based on the number of simultaneous usages acquired (equivalent to purchasing multiple copies of a single title). For example, if a library acquires a title with rights to a single user at a time, then that item is counted as 1 “unit”; if the library acquires rights to a single title for 10 simultaneous users, then that item is counted as 10 “units.” For smaller libraries, if volume data are not available, the number of titles may be counted.

Unlimited simultaneous use: units of acquisition or purchase is based on the number of titles acquired. For example, if a library acquires a collection of 100 books with unlimited simultaneous users, then that collection would be counted as 100 “units.”

**Rationale for deletion**: This data element, along with 451 (Electronic Books – Ebooks) and 453 (Audio – downloadable Units), sow confusion and inconsistency, as the line between distinctly selected “materials” and subscription “collections” blurs. This has led to mixed guidance among states and confusion among library respondents, rendering survey results less reliable.

As products frequently change their model of delivering content, and often offer multiple products under different delivery models (e.g. some pay-per-use, some not), it becomes increasingly unwieldy to track what a collection looks like from year to year. Additionally, as greater emphasis is placed on e-resources as a type of service, it would be useful to align the corresponding data elements to better reflect this. Last, e-books, e-audio, and e-video circulation, and the corresponding expenditures, can effectively reflect ROI for libraries, while still allowing for analysis of national trends. These data elements alone offer a better picture of how these products are being used, than simply counting them according to inconsistent and ever-changing guidance.

_Note: The survey can continue to highlight eBooks, downloadable audiobooks and downloadable video use under amended data element 552._

**Comment by Chilcoat** [comment]
I agree with the change.  Our holdings numbers for e-materials are next to meaningless, since nearly every library in the state belongs to one consortium or another and are sharing their titles.  I think this would eliminate a lot of work and gnashing of teeth from our reporting libraries, too.
