### ISSUE TITLE
Revision: 555 Electronic Content Use (ELCONT)

### ISSUE THREAD

**Issue by KathleenSullivan** [IMLS/public-libraries-survey#46]
**Your names**: Kathleen Sullivan (WA), on behalf of the SDC Electronic Materials FAQ Working Group (Yana Demireva (MD), Chris Guerra (AZ), Joseph Hamlin (MI), Kelly Metzger (RI), Kathleen Sullivan (WA))

**Number of data element you seek to change**: 555 Electronic Content Use (ELCONT)

**Proposed change:** Electronic content use would reflect circulation of all items with a loan period, along with the number of times a service with no loan period is accessed.

**Rationale for change**: This value is a more accurate representation of total electronic content usage due to its avoidance of making complex and inconsistent determinations on what should be counted.

**Comment by Chilcoat** [comment]
Sorry if I haven't been paying attention, but I need clarification.  Currently, #555 is the sum of #552 and #554.  How is "the number of times a service with no loan period is accessed" different from the current #554, "The number of full-content units or descriptive records examined, downloaded, or otherwise supplied to user, from online library resources that require user
authentication but do not have a circulation period"?

**Comment by timrohe** [comment]
I want to make sure I understand this correctly.  For stuff like e-Books and streaming music and video, we're no longer trying to count units.  We're just counting usage: how many e-Books, movies, etc. downloaded from platforms like OverDrive and Kanopy.  Correct so far?  Then, for electronic collections, we're counting the number of collections and, with these changes, the number of logins.  Still good so far?  If so, when it comes to engagement with these services, you're counting apples (usage) and oranges (access).  They're two different types of engagement, with usage of electronic materials being a more precise measurement than logins to electronic collections.  Therefore, in my mind, it no longer really makes sense to combine them into one totaled data element, 555 Electronic Content Use.

**Comment by KathleenSullivan** [comment]
@timrohe. Close. Overall, we're proposing to make all electronic content one thing (no more "materials" vs "collections," but only "products"), and then having two different counts of use, depending on whether the product *loans* the content or doesn't. If the product has a loan period for its eBooks, downloadable audiobooks, downloadable video or downloadable other content (music, scores etc), then we count each loaned item as one use, and these can continue to break down by subcategory (how many eBooks, video etc). If the product doesn't have loan periods, we count each patron login as one use. The combined counts -- total loaned items + total logins -- is captured in this 555 data element.

**Comment by timrohe** [comment]
@KathleenSullivan Thank you for clearing that up.  I still feel like you're totaling apples and oranges at the end, though.

**Comment by ghost** [comment]
Again, I agree with @timrohe.

**Comment by enielsen-air** [comment]
I think the comments above actually belong to issues #44 and #45.  It is not apparent to me that the changes to data elements 552 and 554 could require a change to the _definition_ of data element 555.  The current definition reads, "The total annual count of the circulation of electronic materials and the successful retrieval of electronic information (Data elements #552 and #554)." However, it does sound like if the change to data element 554 (#45) were to move forward, the validity of data element 555 (and 556 for that matter) may be in question, and thus it may be appropriate to delete those two data elements.

**Comment by VTLIB1** [comment]
I mean, this question (and 556) has always been apples and oranges, hasn't it? Treating e-circulation and database retrievals as fully equivalent is a little dubious, like adding reference questions and website visits to get...something? Switching to logins just magnifies the preexisting difference, though I agree with Evan that we might be better served by deleting 555 and 556. But frankly, I'd like to do that either way. (Josh)

**Comment by timrohe** [comment]
I'm getting a little confused about what we're debating.  I would think that deleting 555 and 556 is NOT on the table because it was not officially raised in any of the various proposals and the deadline for submitting proposals has passed.  If someone did want to propose that, they would have to wait until next year.  Can anyone confirm that?

**Comment by az-cguerra** [comment]
@timrohe  My understanding is exactly as you've stated, that the deletion of 555 and 556 are not currently on the table for this year.

Going back to your initial point that it combines apples and oranges (which I agree with), I have to parrot Josh in saying that it's always been the case. Unfortunately, I wasn't part of the initial discussion that led to the creation of 555 and 556, so I'm not sure what the expectation of those data elements were. Nonetheless, I'm all in favor of proposing to delete them next year unless someone can help me understand what real value they provide. They both feel so arbitrary.
