### ISSUE TITLE
Revision - 630 Total Views of Asynchronous Program Presentation within Days (TOTVIEWS)

### ISSUE THREAD

**Issue by rfuquaSLO** [IMLS/public-libraries-survey#49]
**Submitted by:**
Ross Fuqua, SDC, State Library of Oregon

**Existing Data Element:**
- 630 Total Views of Asynchronous Program Presentation within 7 Days (TOTVIEWS)

**Current Definition:**
The count of views of asynchronous program presentations for a period of seven (7) days after the presentation was posted, even if that period extends beyond the survey reporting period (or fiscal year). For program presentations made available via Facebook, count unique 1-minute views of each video. For those made available via other platforms, count unique views of each video.
For program presentations that are recordings of synchronous virtual program sessions, exclude synchronous attendance; these should be counted under Synchronous In-Person Onsite Program Attendance, Synchronous In-Person Offsite Program Attendance, or Synchronous Virtual Program Attendance (data elements 616, 617, or 618).

**Revised Definition:**
The count of views of asynchronous program presentations for a period of **_thirty (30)_** days after the presentation was posted, even if that period extends beyond the survey reporting period (or fiscal year)....

**Rationale:**

- Most public libraries I have consulted with about this new element (630) have expressed that the 7-day period for this particular type of metric is too limited and is of little local value. Many libraries track (and report to their local governing bodies) a variety of engagement metrics from social media platforms on a monthly basis. Given that most asynchronous views of library programs occur via social media platforms like Facebook and YouTube, tracking an additional 7-day view metric solely for the purposes of reporting on the PLS creates an additional burden for libraries without adding value to that data locally.
- The 7-day tracking period is especially problematic for small public libraries. Many of these libraries -- if they are able to devote any staff time to virtual programs at all -- are only able to create one or two virtual programs each month. A 7-day viewing period seems biased toward larger, urban libraries that are better resourced to create and post new program content on a daily or weekly basis.

**Comment by mariabernier10601** [comment]
30 days is more consistent with the period that my media-savvy libraries look at. But if we change this timeframe, we need to stick with it for the long haul.

**Comment by JHoganHI** [comment]
Libraries here support extending the time period. They also post new content on more of a monthly basis. Jessica H. (HI)

**Comment by timrohe** [comment]
If we're going to change the definition, why not just change the time frame to the entire reporting period, or until it's taken down?  I don't understand why there's a cap on it at all.  Sure, the majority of views may come within the first 7 or 30 days, or whenever, but that doesn't mean that any views that happen after shouldn't count.  What if the library reposts a link to an older video and it gets more views?  Do we just tell them, "Sorry, that doesn't count because it wasn't in the first 30 days?"  It all just seems arbitrary.
