### ISSUE TITLE
Proposed addition: Website visits

### ISSUE THREAD

**Issue by lhofschire** [IMLS/public-libraries-survey#5]
Name: Linda Hofschire
State: Colorado

Title of the proposed data element: Unique visits to library website.

Definition: Visits represent the number of unique sessions initiated by all visitors from inside or outside the library. Include the library OPAC or library webpage. [This definition was developed by SDCs at the 2015 Annual meeting]

Rationale for addition: To accurately tell the story of the 21st century library and to document shifts in usage from physical to virtual.

States that are already collecting this information: Multiple, including Colorado

**Comment by jrnelson1201** [comment]
Can you say more about including visits to the OPAC? It seems a little different to me than visits to library webpage.

**Comment by lhofschire** [comment]
Good question! I've posted to the SDC list to confirm the reason for this. It may have been for situations where the library's only online presence was its OPAC.

**Comment by lhofschire** [comment]
Just wanted to confirm that OPAC visits was included in this definition for instances where the library's only online presence was its OPAC.
