### ISSUE TITLE
Deletion: 451 ebooks, 453 downloadable audio, and 455 downloadable video

### ISSUE THREAD

**Issue by mariabernier10601** [IMLS/public-libraries-survey#50]
**Submitter:** Maria Bernier (CT), on behalf of the SDC Electronic Materials FAQ Working Group (Yana Demireva (MD), Chris Guerra (AZ), Joseph Hamlin (MI), Kelly Metzger (RI), Kathleen Sullivan (WA))

**Existing Data Elements:**
•	451 Electronic Books – Ebooks 
•	453 Audio – downloadable units 
•	455 Video – downloadable units 

**Rationale:** 
This proposal is one of five interrelated proposals for changes and additions to electronic content, which was formerly divided into electronic materials and electronic collections. The SDCs have long indicated a need to make these counts obtainable and make the elements more consistently interpreted. 

These three data elements should be deleted. They sow confusion and inconsistency, as the line between distinctly selected electronic “materials” to be counted here and subscription electronic “collections” to be counted elsewhere blurs. This has led to mixed guidance among states and confusion among library respondents, rendering survey results less reliable. As vendors frequently change their model of delivering content, and often offer multiple products under different delivery models (e.g. some pay-per-use, some not), it becomes increasingly unwieldy to track individual holdings from year to year and distinguish them from electronic collections. 

Also, under the current definitions, libraries are directed to count items that were purchased, leased or licensed by their consortium and by their state library in addition to their own holdings. This results in overcounting and substantially distorts the number of holdings statewide. As one state commented last year: “Our holdings numbers for e-materials are next to meaningless, since nearly every library in the state belongs to one consortium or another and are sharing their titles.” 

New proposed data elements counting circulation of electronic materials would offer a better picture of how these products are being used, rather than simply counting them according to inconsistent and ever-changing guidance.

The three data elements in this proposal should be deleted or retained as a set.

[PLS changes summary.docx](https://github.com/IMLS/public-libraries-survey/files/7048735/PLS.changes.summary.docx)
[ElectronicContentFlowChart.pdf](https://github.com/IMLS/public-libraries-survey/files/7048736/ElectronicContentFlowChart.pdf)

**Comment by VTLIB1** [comment]
I think this is a great idea. At present, we're counting a portion of the market (no pay-per-use), but we're counting it over and over again (consortiums). So I don't know what those numbers could mean.

**Comment by mariabernier10601** [comment]
Including items in a holdings count that were purchased, leased or licensed by a library's consortium or by their state library has never made sense to me. We don't do that with physical items, so why would we do it with electronic items? For instance, I would never tell a library to include all the books in the state library's print collection as part of their own holdings. It's illogical.
