### ISSUE TITLE
Revision: Electronic Collections (456 Local/Other cooperative Agreements, 457 State Electronic Collections, 458 Total Electronic Collections)

### ISSUE THREAD

**Issue by mariabernier10601** [IMLS/public-libraries-survey#51]
**Submitter:** Maria Bernier (CT), on behalf of the SDC Electronic Materials FAQ Working Group (Yana Demireva (MD), Chris Guerra (AZ), Joseph Hamlin (MI), Kelly Metzger (RI), Kathleen Sullivan (WA))

**Existing Data Elements:**
•	456 Local/Other cooperative Agreements  
•	457 State (state government or state library) Electronic Collections  
•	458 Total Electronic Collections

**Rationale:** 
This proposal is one of five interrelated proposals for changes and additions to electronic content, which was formerly divided into electronic materials and electronic collections. The SDCs have long indicated a need to make these counts obtainable and make the elements more consistently interpreted. 

The intent of these changes is to measure something a bit more measurable.  

We propose to make all electronic content one thing (no more "materials" vs "collections" or “databases” but only "products"), and then have two different counts of use, depending on whether the product loans the content or doesn't. If the product has a loan period for its eBooks, downloadable audio, downloadable video or downloadable other content (maps, scores etc), then we count each loaned item as one use, and these can be broken down by subcategory (how many eBooks, video etc). If the product doesn't have loan periods, we count either each session or each search as one use.

The reason we went with electronic circulation and access of electronic products is two-fold: (1) on the surface, they're conceptually easy to understand (Did it circulate/download? Did they login or do a search?); and (2) they're the most likely to be aggregable data that we can collect. With this and the other proposals we've put forth, what we're saying is "here are the number of electronic products libraries are paying for;" "here is the number of times people are going out of their way to use the product;" and "here is the number of times people are circulating/downloading individual e-books, audiobooks, music, and videos."

Counting each collection as a single product provides a value that is reliable in its accuracy as well as aggregable at the national level. It removes the need to make annual determinations of whether a product’s offerings should be considered an electronic “collection” in 456 and 457 or individual electronic “material” reported in 451, 453, and 455 – a determination that already lacks merit due to the existing mash-up of offerings that can be provided in a single product.

Larger electronic "collections" would be reflected in expenditures for electronic content, as well as usage, whether through circulations or sessions. As an example, a large system with hundreds of thousands of Overdrive titles would have larger expenditures and higher usage statistics.

In addition, we propose to rename 457 and 458 from Electronic Collections to Electronic Products. 

The proposed revised description applies to all three elements (456 Local/Other cooperative Agreements, 457 State (state government or state library) Electronic Products, and 458 Total Electronic Products), and therefore its approval would affect all three elements.

Proposed new names for elements:
•	457 State (state government or state library) Electronic Collections Products
•	458 Total Electronic Collections Products

**Proposed Definitions:**
See attachment, as this interface does not allow sufficient formatting options.

[456-457-458.docx](https://github.com/IMLS/public-libraries-survey/files/7048755/456-457-458.docx)
[PLS changes summary.docx](https://github.com/IMLS/public-libraries-survey/files/7048756/PLS.changes.summary.docx)
[ElectronicContentFlowChart.pdf](https://github.com/IMLS/public-libraries-survey/files/7048757/ElectronicContentFlowChart.pdf)

**Comment by benmillerWI** [comment]
Document 456-457-458.docx notes that Electronic (Products) can include, for example, both Explora and an individual database that may be included in Explora such as Academic Search Premier. Wisconsin currently includes only individual databases and not specialized interfaces (grouping of individual databases) in the Collections count. 
1. Does this new definition mean the Product count could include both or should include both?
2. If interfaces are included in the overall count, how does that relate to the tracking of Searches or Sessions? Would a library include data from both an individual database as well as the interface report, and if so, how does this address duplication of usage?

**Comment by yanademireva** [comment]
I think this would definitely require consideration because there is already inconsistency. As an example, in MD we purchase Gale OneFile, which has several different titles, but is purchased as one product - so that's one; however, we also purchase Gale in Context for High School/Middle School/Elementary. These are three products, purchased separately, even though they are under the same general series title. I would have to do some digging to see how the usage report comes through - whether by each individual OneFile database, or just for the whole thing. Also hoping maybe someone else in the group can provide further thoughts?

**Comment by timrohe** [comment]
> Document 456-457-458.docx notes that Electronic (Products) can include, for example, both Explora and an individual database that may be included in Explora such as Academic Search Premier. Wisconsin currently includes only individual databases and not specialized interfaces (grouping of individual databases) in the Collections count.

That's how we count them in NH as well.  I am not in favor of counting the specialized interfaces.  I don't see the value in it and have the same concerns raised about how this would affect the tracking of searches or sessions.
