### ISSUE TITLE
Addition: Four elements for Circulation of Electronic Content by material types 

### ISSUE THREAD

**Issue by mariabernier10601** [IMLS/public-libraries-survey#53]
**Submitter:** Maria Bernier (CT), on behalf of the SDC Electronic Materials FAQ Working Group (Yana Demireva (MD), Chris Guerra (AZ), Joseph Hamlin (MI), Kelly Metzger (RI), Kathleen Sullivan (WA))

**New Data Elements:** 
•	Ebook circulations
•	Downloadable audio circulations
•	Downloadable video circulations
•	Other downloadable material circulations

**Rationale:** 
This proposal is one of five interrelated proposals for changes and additions to electronic content, which was formerly divided into electronic materials and electronic collections. The SDCs have long indicated a need to make these counts obtainable and make the elements more consistently interpreted. 

We propose to make all electronic content one thing (no more "materials" vs "collections" or “databases” but only "products"), and then have two different counts of use, depending on whether the product loans the content or doesn't. If the product has a loan period for its eBooks, downloadable audio, downloadable video or downloadable other content (maps, scores etc), then we count each loaned item as one use, and these can be broken down by subcategory (how many eBooks, video etc). If the product doesn't have loan periods, we count either each session or each search as one use.

The reason we went with electronic circulation and access of electronic products is two-fold: (1) on the surface, they're conceptually easy to understand (Did it circulate/download? Did they login or do a search?); and (2) they're the most likely to be aggregable data that we can collect. With this and the other proposals we've put forth, what we're saying is "here are the number of electronic products libraries are paying for;" "here is the number of times people are going out of their way to use the product;" and "here is the number of times people are circulating/downloading individual e-books, audiobooks, music, and videos."

We propose to add itemized circulation counts for ebooks, eaudio, evideo and e-other to get an accurately summed Circulation of Electronic Content. Count as one use the circulation of any electronic content with a loan period. Simply, if it has a circulation period, count it by type (e-book, video, etc.).

The definitions below are largely copied from 451 Electronic Books – Ebooks, 453 Audio – downloadable units, and 455 Video – downloadable units. 

The four data elements presented in this proposal represent four exhaustive and mutually exclusive categories that would sum to the revised element 552 Circulation of Electronic Content. Thus, they should be approved or rejected as a set.

**Proposed Definitions:**
See attachment, as this interface does not allow sufficient formatting options.
[e-circ.docx](https://github.com/IMLS/public-libraries-survey/files/7048777/e-circ.docx)
[PLS changes summary.docx](https://github.com/IMLS/public-libraries-survey/files/7048779/PLS.changes.summary.docx)
[ElectronicContentFlowChart.pdf](https://github.com/IMLS/public-libraries-survey/files/7048780/ElectronicContentFlowChart.pdf)

**Comment by VTLIB1** [comment]
I like this option as well. I think it makes sense to add granularity on the circulation side, rather than the holdings side, since it shows what's actually getting used.
