### ISSUE TITLE
Addition and Deletion: Sessions (or Searches) of Electronic Content, Successful Retrieval of Electronic Information (554), Electronic Content Use (555) and Total Collection Use (556)

### ISSUE THREAD

**Issue by mariabernier10601** [IMLS/public-libraries-survey#54]
**Submitter:** Maria Bernier (CT), on behalf of the SDC Electronic Materials FAQ Working Group (Yana Demireva (MD), Chris Guerra (AZ), Joseph Hamlin (MI), Kelly Metzger (RI), Kathleen Sullivan (WA))

**New Data Elements:** 
•	EITHER Sessions of Electronic Content OR Searches of Electronic Content

**Existing Data Elements:**
•	554 Successful Retrieval of Electronic Information 
•	555 Electronic Content Use 
•	556 Total Collection Use 

**Rationale:** 
This proposal is one of five interrelated proposals for changes and additions to electronic content, which was formerly divided into electronic materials and electronic collections. The SDCs have long indicated a need to make these counts obtainable and make the elements more consistently interpreted. 

The intent of these changes is to measure something a bit more measurable.  

We propose to make all electronic content one thing (no more "materials" vs "collections" or “databases” but only "products"), and then have two different counts of use, depending on whether the product loans the content or doesn't. If the product has a loan period for its eBooks, downloadable audio, downloadable video or downloadable other content (maps, scores etc), then we count each loaned item as one use, and these can be broken down by subcategory (how many eBooks, video etc). If the product doesn't have loan periods, we count either each session or each search as one use.

The reason we went with electronic circulation and access of electronic products is two-fold: (1) on the surface, they're conceptually easy to understand (Did it circulate/download? Did they login or do a search?); and (2) they're the most likely to be aggregable data that we can collect. With this and the other proposals we've put forth, what we're saying is "here are the number of electronic products libraries are paying for;" "here is the number of times people are going out of their way to use the product;" and "here is the number of times people are circulating/downloading individual e-books, audiobooks, music, and videos."

1. We propose to delete 554 Successful Retrieval of Electronic Information and replace with a new element, EITHER Sessions of Electronic Content OR Searches of Electronic Content. Libraries would count sessions or searches instead of the number of individual items or documents downloaded or viewed. This eliminates the current definition’s emphasis on patrons sufficiently viewing/examining/downloading “full” content, which is confusing or impossible to track among dozens of products and results in unreliable and inconsistent counts.

The proposed definitions for Sessions of Electronic Content and Searches of Electronic Content refer to either sessions or searches, which are included in the four measures of use of electronic collections detailed in Z39.7. See ANSI/NISO Z39.7-2013, Information Services and Use: Metrics and Statistics for Libraries and Information Providers — Data Dictionary

2. We propose to delete both 555 Electronic Content Use and 556 Total Collection Use. 

555 Electronic Content Use was formerly the sum of 552 Use of Electronic Material and 554 Successful Retrieval of Electronic Information. With the deletion of 554 Successful Retrieval of Electronic Information, this sum is no longer valid. Nor does it make sense to create a new element adding Use of Electronic Material and Sessions of Electronic Content, as those two elements are unlike. 

556 Total Collection Use was formerly the sum of 552 Use of Electronic Material, 553 Physical Item Circulation, and 554 Successful Retrieval of Electronic Information. With the deletion of 554 Successful Retrieval of Electronic Information, this sum is no longer valid. 

It seems people really want a national value of some kind to reflect electronic usage for trend and comparison purposes. The problem is that the sheer complexity of electronic content availability and usage does not lend itself well to generating all-encompassing values. Instead, circulation values along with our proposal to count the number of times an electronic product is accessed or searched would be how we track overall usage. When viewed together, 550 Total Circulation of Materials (sum of 552 and 553) as well as the new element Sessions of Electronic Collection would show the whole scope of circulation and use.

Because of the interrelation among these data elements, they should be approved or rejected as a set.

**Proposed Definitions:**

EITHER
•	Sessions of Electronic Content

For electronic products that offer content with no loan periods, count as one use a single session by an authenticated user (e.g., a patron logs in to Freegal).

A session is defined as a successful request of a database. It is one cycle of user activities that typically starts when a user connects to a database and ends by terminating activity in the database that is either explicit (by leaving the database through log-out or exit) or implicit (timeout due to user inactivity). [From Z39.7-2013, item 7.7 Use]

OR
•	Searches of Electronic Content

For electronic products that offer content with no loan periods, count as one use a single search by an authenticated user (e.g., a patron logs in to Freegal).

A search is defined as intending to represent a unique intellectual inquiry. Typically, a search is recorded every time a search request is submitted to the server. [From Z39.7-2013, item 7.7 Use]

[PLS changes summary.docx](https://github.com/IMLS/public-libraries-survey/files/7048840/PLS.changes.summary.docx)
[ElectronicContentFlowChart.pdf](https://github.com/IMLS/public-libraries-survey/files/7048841/ElectronicContentFlowChart.pdf)

**Comment by kjcmetzger** [comment]
While I agree that using a single metric like Sessions would make more sense, I do wonder if that truly captures usage of the tutorial/module/course type of electronic products (i.e., Udemy, Universal Class, etc.). If not, is that something that should be addressed, and if so, how?

**Comment by VTLIB1** [comment]
I continue to be in favor of this solution (sessions being my preference). It's not perfect, but I think the only perfect approach is to break out every single vendor. I think sessions (especially) creates a much more apples-to-apples comparison than full text retrievals.

**Comment by kdnorthrup** [comment]
> 
> 
> While I agree that using a single metric like Sessions would make more sense, I do wonder if that truly captures usage of the tutorial/module/course type of electronic products (i.e., Udemy, Universal Class, etc.). If not, is that something that should be addressed, and if so, how?

This will be a tricky transition for us as well. We currently count Lessons Viewed for Universal Class. Switching to Login Sessions would decrease usage to about 25% of what it is now. At the state level, we'll need to track both for at least a few years for accurate trends and ROI analysis. But nevertheless, this proposed change is a big improvement overall.

**Comment by benmillerWI** [comment]
I generally agree that the current requirement and definition is unsustainable due to the lack of guidance on applicable metrics. In Wisconsin we developed our own interpretation of 554 for state-provided databases, and as time allowed, guidance to the community for locally purchased content. This resulted in a mixed bag of metrics that most closely aligned with a successful retrieval, whether or not it led to full-text content, as it isn’t relevant/applicable for all products. Most libraries became confused and overwhelmed. 

I also agree that simplifying and defining specific metrics is ultimately a move in the right direction, however I have some questions that could help alleviate any further confusion or issues when attempting to compare, if possible, use of a particular product/database across states. Or even with setting some consistency for further analysis within a state.

1. Will there be guidance or recommendations on which report to use? For example, “If the vendor provides multiple reporting options, use COUNTER reports when available, beginning with the latest release (currently R5).”
2. Will there be guidance or recommendations on which metric to use for a particular vendor if they provide both Searches and Sessions in the same report?  
3. Will there be guidance on counting Searches, specifically for COUNTER reports? For example, should libraries enter the combined total of all available Search metrics (Searches_Regular, Searches_Federated, Searches_Automated)?   
4. I agree with the question posed by kjcmetzger about usage of products that don’t neatly fall into Searches/Sessions. Another example is LearningExpress Library. While they provide a Sessions metric, the actual use of their content is reflected in the Total # of Resources metric as this tallies the “launch” of a specific item. How is this being addressed?

**Comment by yanademireva** [comment]
@benmillerWI, my initial thought is that we wouldn't provide guidance on specific products. The reason to use sessions/searches is that we believe most products provide one of these metrics. For those that don't, the nearest available would be good enough. We could also add, as @kjcmetzger suggests, something in the guidance for tutorial-type products specifically, without getting too in the weeds. It's not tenable to continuously update the guidance (hence the sessions/searches). I do think COUNTER reports would be a good standard.

**Comment by vdgreenwood** [comment]
Let me add a fly in this ointment....**FWIW**

I copied Maria's proposal and ran it by our Resource Sharing SME.  We have struggled a great deal within Texas, trying to determine the "best" way to measure usage.  Here is her perspective.

> Searches and Sessions are both unreliable measures, in my view. They are predicated on the idea that a patron logs in to a vendor website and that all of their activity occurs there. In a library that uses a federated search tool (like our old Library of Texas or the tool that comes with SirsiDynix Enterprise, for example), either a session and search is logged for EVERY database that is searched at once, dramatically inflating numbers, or NO session is logged at all (though searches remain inflated). That’s why Texas decided not to use those metrics for our LBB reporting.
> 
> Large public libraries, like academic libraries, are now using what are called discovery services, and there the problem gets even worse. The searchable index of content available in an e-resource is stored on a platform, like EBSCO Discovery Service (EDS) that libraries subscribe to. Users search that discovery platform, and all sessions and searches are logged there. The vendor platform doesn’t even know that there is activity until a user requests full-text. The fact that academic libraries have almost all adopted these platforms is a major reason for the ongoing decline we see in TexShare usage numbers. Several states have implemented statewide discovery systems, so their reported use will be questionable.
> 
> Even worse, most discovery services are configured so that users don’t have to log in to perform a search, so their definition (a search is one request made by an authenticated user) means that a lot of activity wouldn’t be counted. 
> 
> Finally, unless a vendor adopts [COUNTER](https://www.projectcounter.org/), their system will track searches by robots and other automated systems for both federated searches and discovery systems, which will drastically inflate the search totals. COUNTER, which is the internationally recommended best practice for tracking e-resource usage is one that the major vendors and most large libraries (public and academic) have already adopted.
> 
> If they have to go with one metric, though, I’d still suggest search. The COUNTER definition is “A user-driven intellectual query, typically equated to submitting the search form of the online service to the server.” COUNTER-compliant tracking excludes robots, and it offers the ability to split out “regular” searches from federated searches. The definition of a regular search is “A search conducted by a user on a host where the user is in control over which databases can be searched.”
> 
> Or they can stick with the retrievals concept and use the COUNTER definition, which is now called a request (since a significant amount of use comes from streaming media, they retired the “Full-Text Retrieval concept). A request is defined as “A category of COUNTER Metric Types that represents a user accessing content (i.e. full text of an article).”

**Comment by kjcmetzger** [comment]
@vdgreenwood That is actually really helpful. I'm encouraged by the fact that COUNTER has retired the "Full-Text Retrieval" concept to adapt to streaming media. If we adopt the COUNTER definitions, it would enable libraries to identify the metrics that best match those definitions, even if a vendor is not COUNTER-compliant.

Does anyone know how COUNTER handles tutorial-type products?

**Comment by vdgreenwood** [comment]
@kjcmetzger:  once again, I turned to my Resource Sharing Administrator (Danielle Plumer)

> Interactive products, like LearningExpress, are not COUNTER-compliant because COUNTER makes no special provision for them. We’ve struggled with how to track their usage. Right now we combine various items from the vendors’ standard usage reports to create things similar to our standard metrics that correspond pretty well to COUNTER investigations and requests.
> 
> By and large, these resources require patrons to set up individual accounts on the platform so that the tool can track up progress through a multi-page tutorial and the like. Sessions are a pretty reliable measure also, with one big exception that I’ll describe later.
> 
> Searches mean very little in these platforms, as they are based on browsing. I’ve tried to persuade vendors that “browsing” = “search” here, so that clicking on a button labeled “Technical Careers,” for example, is exactly equivalent to performing a search for “Technical Careers,” but I haven’t had any luck.
> 
> For item requests/retrievals, the difficultly is in identifying the unit of measure. It’s easy to track tutorials completed, especially if you’re only looking at successful completions (e.g., passing grades). Tutorials completed with a failing grade are trickier, because users can usually go back and fix the things they got wrong, and most (but not all) users will do so if they got to that point. You might end up double-counting something as a result.
> 
> However, there is no consistent way to track progress through a tutorial. You could track the number of times a registered user begins a tutorial, I suppose, but there is a very high rate of abandonment in LearningExpress and other tutorial resources we’ve used.

**Comment by yanademireva** [comment]
Thanks @vdgreenwood for these insights - I think this is really useful info to have, especially around the COUNTER definitions, which seem to be a great starting point for revising the PLS definitions. My thoughts on tutorial-based products would be that, it's really not within the scope of the PLS to track whether someone is successful in completing the tutorial, or passing it, etc. So, something equivalent to number of tutorials started or completed (or whatever the actual metric is) would be a "good enough" metric, perhaps.
