### ISSUE TITLE
Revision - 204 Geographic Code

### ISSUE THREAD

**Issue by enielsen-air** [IMLS/public-libraries-survey#55]
**SUBMITTER:**
Evan Nielsen, AIR

**EXISTING DATA ELEMENT:**
204 Geographic Code (GEOCODE)

**RATIONALE:**
The current options for Geographic Code do not align with the geographies for which the Census Bureau produces population estimates.  In particular, incorporated municipalities (e.g., cities and villages) are a different category than county subdivisions (or minor civil divisions, e.g., towns and townships, the terminology for which varies by state and region).  Also, the "Metropolitan Area" (MA1 or MA2) was only selected for 18 AEs in FY19, and several of those appear to be in error, so those two categories do not appear to be necessary to retain.  Thus, the revised definition below includes a modified definition to improve clarity, and adds four new categories (UP1, UP2, CD1, CD2) while revising two (CI1, CI2) and removing two (MA1, MA2).

**CURRENT DEFINITION:**
Choose from among the following types of readily available Census geography, one code that either exactly or most nearly describes the geographic area for which the public library has been established to offer services and from which (or on behalf of which) the library derives revenue, plus any areas served under contract for which the library is the primary service provider.
Note: The Population of Legal Service Area (data element #208) should be reflected in the geographic code selected. For further clarification of municipal government, county/parish, and school district, refer to definitions under Legal Basis Code (data element #201).
CI1—Municipal Government (city, town or village) (exactly)
CI2—Municipal Government (city, town or village) (most nearly)
CO1—County/Parish (exactly)
CO2—County/Parish (most nearly)
MA1—Metropolitan Area (exactly)
MA2—Metropolitan Area (most nearly)
MC1—Multi-County (exactly)
MC2—Multi-County (most nearly)
SD1—School District (exactly)
SD2—School District (most nearly)
OTH—Other

**NEW DEFINITION:**
Choose one of the following types of geography (defined by the U.S. Census Bureau) that best describes the legal service area for which the public library has been established to offer services and from which (or on behalf of which) the library derives revenue, plus any areas served under contract for which the library is the primary service provider. The Geographic Code should represent the basis for the Population of Legal Service Area (data element #208), including areas served under contract. Each geography type has two subtypes: "exactly" and "most nearly." If the legal service area does not match one of the geography types exactly, select the "most nearly" option for the geography type that is most similar.
Note: For further clarification, see the definition of terms published by the U.S. Census Bureau:  https://www.census.gov/programs-surveys/popest/guidance-geographies/terms-and-definitions.html
CI1—Incorporated Place (e.g., city, village) (exactly)
CI2—Incorporated Place (e.g., city, village) (most nearly)
UP1—Unincorporated Place (exactly)
UP2—Unincorporated Place (most nearly)
CD1—Minor Civil Division (e.g., town, township) (exactly)
CD2—Minor Civil Division (e.g., town, township) (most nearly)
CO1—County/Parish (exactly)
CO2—County/Parish (most nearly)
MC1—Multi-County (exactly)
MC2—Multi-County (most nearly)
SD1—School District (exactly)
SD2—School District (most nearly)
OTH—Other

**Comment by enielsen-air** [comment]
In full transparency, this proposal still needs some work (particularly around guidance for selecting "Other"). I wanted to propose it in draft form to allow for consideration for FY22.

**Comment by mariabernier10601** [comment]
Please explain the necessity to align some of the answer choices with Census terminology while other answer choices (e.g. unincorporated, multi-county, and school district) are not aligned. Will this change make the PLS data more usable in combination with Census data? What about data for libraries with geographic codes that don't map to a specific Census term -- how would their data be used in combination with Census data?

In a New England state, this change would require a significant education effort to help 178 AEs decide whether they are incorporated places or MCDs. I need to see that there's sufficient reason and logic to justify this workload.

**Comment by enielsen-air** [comment]
Good questions, @mariabernier10601. The Census Bureau is continually changing their data products, and it appears that this data element hasn't been updated to match for some time (maybe Jay Bank can speak to when). If the response options for this item don't align with available Census data products, then we should question why it should stay on the survey and data files.

I also want to preface my specific responses below by admitting an assumption that, in many (most?) states, it is the SDCs that decide the GEOCODE value for all AEs, and thus the burden of this change would not fall on respondents in individual libraries. That said, it sounds like this is not the case in Connecticut.

The distinction between incorporated and unincorporated is due to the fact that the annual vintage population estimates from Census are only available for incorporated places, whereas American Community Survey (ACS) estimates are available for both.  It may turn out that this distinction is unnecessary; the more important separation is between places (cities & villages) and county subdivisions (townships/towns), since these estimates are categorized separately in Census datasets. Based on your point about your 178 AEs, I would say I'm now leaning toward collapsing all "places" (incorporated and unincorporated).

School districts are available Census geographies, although population estimates also are only available from the ACS.

For multi-county, this is where I'm torn. It is helpful to know if the legal service area is a single county or more than one when merging with Census data; however, this is true for other geographies as well: if a library serves multiple townships or cities, it would be good to capture that. I'm not sure of the best way to capture this yet, and I don't think it is as easy as considering the Legal Basis Code along with the Geographic Code.

**Comment by az-cguerra** [comment]
@enielsen-air, I just want to add that in Arizona we've always had the libraries select their geographic code (at least so long as I've been doing this). I'm kind of curious now to know if I'm in the minority along with Maria. With that said, however, I'm pretty sure a significant percentage of our libraries don't even bother to look at that data element.

**Comment by timrohe** [comment]
> 
> 
> In full transparency, this proposal still needs some work (particularly around guidance for selecting "Other"). I wanted to propose it in draft form to allow for consideration for FY22.

I get a little worried when I hear that it still needs a little work and that this is just a draft.  Maybe we should wait until it's fully fleshed out to propose it.  I would hate to have it added to the FY2022 survey, realize something isn't working, and then have to rework it or change the guidance for FY2023.  That would be incredibly confusing for the respondents.

**Comment by kjcmetzger** [comment]
@az-cguerra - In RI, this data is carried over from year to year on the survey, so neither I nor the libraries are entering this data annually.

I do not oppose the idea of revising the definition of the GEOCODE. @enielsen-air mentions, "The Geographic Code should represent the basis for the Population of Legal Service Area (data element #208), including areas served under contract." My issue with that is there are 8 municipalities in RI that have more than one library serving their population, but for each, they must use the full municipal population for #208. This is not an accurate reflection of their service area. Would changes to GEOCODE be able to address that?

**Comment by rfuquaSLO** [comment]
All, it looks like @enielsen-air has had a chance to update this proposal (at least since I last looked at it). 

Even though I'm in a state with quite a few AEs that will fall into the "OTHER" category, I'm in full support of this idea overall. The more we could align PLS data with existing geographic boundary data from the US Census, the better. This would allow users to mash-up the two data sources for future analyses that could be incredibly revealing, not just in terms of what library service looks like geographically, but also when compared against the Census's rich demographic data. As more and more of our state institutions and local AEs are trying to make data-driven decisions to address inequity issues, this alignment could be highly valuable.

Full disclosure: I currently assign the Geographic Code values for our AEs based on their LSAs, and I keep pretty tight control over these. Fortunately, they almost never change from year to year.

**Comment by sgoek** [comment]
This revision is very necessary. In PLA's work, we have encountered a lot of errors and problems with the geocode variable that have made it challenging to match libraries to Census areas on a national scale. 

I would suggest also adding a field for the _name_ of the Census geography that is being identified as the closest match. That name is not always the same as the City or County name provided elsewhere. (Even better would be providing the GEOID for the appropriate Census geography, but I recognize that it would present more challenges for libraries and SDCs.)
