### ISSUE TITLE
Addition/Revision - Electronic content data elements

### ISSUE THREAD

**Issue by enielsen-air** [IMLS/public-libraries-survey#60]
**Submitter:**
Evan Nielsen (on behalf of LWSG subcommittee)

**Description of Change:**
This proposal is a placeholder for the work that the LSWG subcommittee for PLS methods is undertaking to revise the existing data elements related to electronic content holdings, usage, and expenditures. The subcommittee may end up proposing addition of new elements and deletion of some existing elements. At a minimum, the subcommittee is reviewing the existing data elements listed below:

_Existing Data Elements:_
354 (ELMATEXP) Electronic Materials Expenditures
451 (EBOOK) Electronic Books – EBooks 
453 (AUDIO_DL) Audio – downloadable units
455 (VIDEO_DL) Video – downloadable units
456 (EC_LO_OT) Local/Other cooperative agreements
457 (EC_ST) State (state government or state library)
458 (ELECCOLL) Total Electronic Collections 
552 (ELMATCIR) Use of Electronic Material
554 (ELINFO) Successful Retrieval of Electronic Information
555 (ELCONT) Electronic Content Use

**Rationale:**
The rationale for these changes is well-documented (see #50, #51, #52, #53, #54 from last year). In sum, these existing data elements are difficult for libraries to report, and the results are difficult to interpret. The lack of consistent categories between holdings, usage, and expenditures also limits the analytic use of these data elements.

**Comment by mariabernier10601** [comment]
It would be good to add 556 (TOTCOLL) Total Collection Use to the list as well, since that's the sum of elements 552, 553, and 554. Changes to any one of those will affect 556.

**Comment by sshawNLC** [comment]
I’d like to propose the deletion of elements 451, 453, and 455. These are numbers for the holdings for eBooks, Audiobooks, and downloadable video. Maria Bernier proposed this change in 2021, and I’d like to add the following:

Rationale: These holdings numbers have always been problematic. For many states, the holdings numbers include over-inflated consortia held titles. In our state, we offer a statewide OverDrive consortium. Libraries participating in the consortium report the holdings numbers on the PLS, and those numbers include at best a snapshot of items that are available to the _**consortium**_ at a point in time (e.g. the end of the FY). It should be noted that the items are not owned in a way similarly to print materials, but rather leased through the vendor (usually per time period or number of uses).

Additionally, one should look at these lending models, for OverDrive and other vendors. When a report is run for holdings numbers, those numbers are good only for that point in time. Some items expire after a specific time (usually 12 or 24 months), while others after a specific number of checkouts. Throughout the FY, those “holdings” may come and go, depending on the lease model. Some checkout lending models allow one checkout at a time for a total of 26-28 checkouts, others allow 100 simultaneous checkouts; so one of these “holdings” may expire in 48 months while another may expire in 48 hours.
