### ISSUE TITLE
Delete Outlet COVID data elements - 715/716

### ISSUE THREAD

**Issue by mgolrick** [IMLS/public-libraries-survey#64]
**Name:** Michael Golrick

**State/Affiliation:** State Library of Louisiana

**Description of Change:**
Delete data elements #715, Number of Weeks and Outlet is Closed Due to COVID-19 (C19WKSCL) and #716 Number of Weeks and Outlet Had Limited Occupancy Due to COVID-19 (C19WKSLO) 

**Current Definitions:**
#715 is the number of weeks during the year that due to the Coronavirus (COVID-19) pandemic, an outlet building was physically closed and the public could not enter, when it otherwise would have been open. 

#716 is the number of weeks during the reporting period that an outlet implemented limited public occupancy practices for in-person services at the library building in response to the Coronavirus (COVID-19) pandemic. 

**Justification:**
Weeks open is already collected in #715. Annotations for that could reflect any COVID-related closures.

**Potential methodological issues:**
Weeks closed will already be captured in #715 - and can be documented in a note. Is #716 still useful as we adjust to the new post-pandemic normal.

**Comment by MFAroWI** [comment]
Wisconsin supports this removal.

**Comment by mariabernier10601** [comment]
Yes please! It's time to delete these.

**Comment by mgolrick** [comment]
As a note, NPR had a story this weekend that the Bureau of Labor Statistics is dropping its collection of COVID information and impact on employment/unemployment.

https://www.marketplace.org/2022/09/05/federal-jobs-survey-will-replace-covid-questions-with-new-queries-about-telework/

**Comment by KristenCooke** [comment]
Arkansas supports this removal.
