### ISSUE TITLE
Delete AE COVID data elements - 510 - 522

### ISSUE THREAD

**Issue by mgolrick** [IMLS/public-libraries-survey#65]
**Name:** Michael Golrick

**State/Affiliation:** State Library of Louisiana

**Description of Change:**
Delete data element #510 - 522

_Current Definition:_
See pages 20-21 of the 2022 definitions posted on the wiki
[https://github.com/IMLS/public-libraries-survey/blob/master/FY%202022%20Data%20Elements.pdf](https://github.com/IMLS/public-libraries-survey/blob/master/FY%202022%20Data%20Elements.pdf)

**Justification:**
These 8 data elements (some numbers were skipped) were added to capture data specific to the lockdown due to COVID-19. They are no longer meaningful.

Potential methodological issues:
Reduces burden for both library and SDC.

**Comment by yanademireva** [comment]
Agree that these are no longer relevant and should be removed.

**Comment by MFAroWI** [comment]
Wisconsin supports this removal.

**Comment by mariabernier10601** [comment]
Yes, delete them all!

**Comment by mgolrick** [comment]
As a note, NPR had a story this weekend that the Bureau of Labor Statistics is dropping its collection of COVID information and impact on employment/unemployment.

https://www.marketplace.org/2022/09/05/federal-jobs-survey-will-replace-covid-questions-with-new-queries-about-telework/

**Comment by KristenCooke** [comment]
Arkansas agrees.
