### ISSUE TITLE
Delete - 653 Website Visits

### ISSUE THREAD

**Issue by VTLIB1** [IMLS/public-libraries-survey#66]
Name:
Joshua Muse

State/Affiliation:
Vermont

Description of Change:
Delete - 653 Website Visits (WEBVISIT)

Current Definition:
Visits represent the annual number of sessions initiated by all users from inside or outside the library to the library website. The library website consists of all webpages under the library’s domain. A website “visit” or “session” occurs when a user connects to the library's website for any length of time or purpose, regardless of the number of pages or elements viewed. Usage of library social media accounts (e.g., Facebook, Twitter, etc.) should not be reported here. Libraries unable to collect a count of their website visits should report “-1” (missing). Libraries without websites should report “-3” (not applicable). (Missing values will be imputed in the final dataset, whereas values of not applicable will not be imputed.)

Justification:
I have yet to hear an especially compelling explanation for the value of this statistic (especially at the federal level). The implication seems to be that it's like a tiny reference question, but for every web visit that ends in "I learned real and valuable information on a topic", there are 20 that end in "I now know your hours/phone number/that you have a fax machine." That's letting people know about a service, not giving them a service. The question tries to give libraries credit for accomplishing something, without being able to verbalize exactly what they've accomplished. Additionally, (like WiFi Sessions) it can be difficult to track, but (unlike WiFi Sessions) it's not a hugely important aspect of contemporary libraries.

Potential methodological issues:
Limited years of data for this question could further diminish its utility.

**Comment by mgolrick** [comment]
I argued against this data element when it was first proposed. Some libraries, if their web site is managed by their parent agency, have a great deal of difficulty collecting this item. In addition, if this is the default page/splash page for each terminal, then the number will not be meaningful since it will duplicate the number of computer users. I have my agency's web page set as the default web page for my laptop and desktop, and probably account for as many as 1,000 hits a week for my agency. This is not a meaningful data element which is sometimes difficult to capture.

**Comment by mariabernier10601** [comment]
Over the past couple of years, I've come around to agreeing that this element doesn't have much use and doesn't say much about how people are getting value from their public libraries.

**Comment by sshawNLC** [comment]
Thanks for submitting this. Massive number that is meaningless at the end of the day. We collected these data before it became a national element, and filtered for robots and spiders, but now, with the current definition, there's no requirement to filter for those website "visits", so we don't. Inflated number overall. Agree this needs to go.

**Comment by MFAroWI** [comment]
Wisconsin agreed with deletion of this element.

**Comment by vdgreenwood** [comment]
Texas concurs!  We have never had accurate data and I do not know that it is being used by anyone anywhere.  Thank you for the submission, Josh!

**Comment by KristenCooke** [comment]
Arkansas agrees with the commenters above that the efficacy of our stats on this element is questionable. I can see where the data could have been useful in the past, but I no longer see that any benefit outweighs the problems that exist with this element.

**Comment by pburglibrary** [comment]
We have had difficulty obtaining this number from libraries in Illinois.  We concur that the value of this item is not worth collecting.
