### ISSUE TITLE
Addition (Jen Nelson Minnesota)

### ISSUE THREAD

**Issue by jrnelson1201** [IMLS/public-libraries-survey#9]
Title: Number of Informal Learning Sessions. Informal learning sessions are planned events that are intended to provide educational experiences to children, youth or adults, whether led by a partner or library staff.  The rationale for adding this element is to help distinguish the emerging role of public libraries as part of a community's educational eco system. Programs, as currently counted, does not distinguish between performances, where the attendee is passive recipient of entertainment and those where an attendee is an active participant in learning. There are differences in the intended outcomes for each program, and adding this element may make it easier to tie outcomes to library input/output data. Not aware of any states currently collection; however, it was the subject of a European library study conducted by EBLIDA.

**Comment by cdtyyz** [comment]
Good idea ... and I think this should include both non-formal and informal learning sessions ... as per the following definition and as per the EBLIDA study (link below)

https://drsaraheaton.wordpress.com/2010/12/31/formal-non-formal-and-informal-learning-what-are-the-differences/

http://www.eblida.org/Activities/KIC/libA4EU/eblida_libad4eu_survey_data_results.pdf

**Comment by mgolrick** [comment]
One thing I keep in mind is something that the person who hired me said - and she was my predecessor - the data elements need to be simple enough to be counted by even the smallest libraries. Some of our libraries have directors without the MLS. If we want complete, meaningful data, it needs to be able to be reported by the smallest of the units.

**Comment by juantlee** [comment]
It may be of interest to see the schema being used by IMLS in the new State Program Report where an ACTIVITY like "Instruction" can be:
1. Program (e.g. a class) = Formal interaction and active user engagement (e.g., a class on computer skills).
2. Presentation = Formal interaction and passive user engagement (e.g., an author’s talk).
3. Consultation = Informal interaction with an individual or group of individuals; the provision of expert advice or reference services to individuals, units, or organizations.
That way, the numbers can be aggregated according to the intended outcome.
